name: Radio
on: [workflow_dispatch]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt-get install -y ffmpeg
          while true; do
            ffmpeg -re -i "https://icecast.liveatc.net/lhr_twr" -vn -acodec libmp3lame -b:a 96k -content_type audio/mpeg -f icecast "icecast://source:Ruzgar3637@sapircast.caster.fm:15295/stream"
            sleep 5
          done
